# Cloud Build configuration for Backend
steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/buhler-demo-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/buhler-demo-backend:latest'
      - '-f'
      - 'Dockerfile.production'
      - '.'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/buhler-demo-backend'

  # Run database migrations
  - name: 'gcr.io/google-appengine/exec-wrapper'
    args:
      - '-i'
      - 'gcr.io/$PROJECT_ID/buhler-demo-backend:$COMMIT_SHA'
      - '-s'
      - '${_CLOUD_SQL_CONNECTION_NAME}'
      - '-e'
      - 'DATABASE_URL=${_DATABASE_URL}'
      - '--'
      - 'npx'
      - 'prisma'
      - 'migrate'
      - 'deploy'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'buhler-demo-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/buhler-demo-backend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_CONNECTION_NAME}'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'DATABASE_URL=database-url:latest'
      - '--set-secrets'
      - 'JWT_SECRET=jwt-secret:latest'
      - '--set-secrets'
      - 'JWT_REFRESH_SECRET=jwt-refresh-secret:latest'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'

substitutions:
  _REGION: europe-west1
  _CLOUD_SQL_CONNECTION_NAME: ${PROJECT_ID}:${_REGION}:buhler-demo-db

timeout: 1200s